print("Hello, please rate these statments from 1 to 5.")
q1 = int(input("I enjoy working in teams."))
q2 = int(input("I like to try new things."))
q3 = int(input("I love to be outside."))
q4 = int(input("I want to travel the world."))
q5 = int(input("School can be way hard for me."))
q_1 = float(input("I enjoy working in teams."))
q_2 = float(input("I like to try new things."))
q_3 = float(input("I love to be outside."))
q_4 = float(input("I want to travel the world."))
q_5 = float(input("School can be way hard for me."))